# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81f71a00afee19dedf28a541477ef23b"
name = "RT COD BOOST 2.0"
handle = "rt-cod-boost-2-0"
application_url = "https://rt-cod-boost-2-0.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_customers,write_customers,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://rt-cod-boost-2-0.onrender.com/auth/callback", 
  "https://rt-cod-boost-2-0.onrender.com/auth/shopify/callback", 
  "https://rt-cod-boost-2-0.onrender.com/api/auth/callback"
]

[pos]
embedded = false