# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81f71a00afee19dedf28a541477ef23b"
name = "RT COD BOOST 2.0"
handle = "rt-cod-boost-2-0"
application_url = "https://twins-missouri-biotechnology-steady.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://twins-missouri-biotechnology-steady.trycloudflare.com/auth/callback", "https://twins-missouri-biotechnology-steady.trycloudflare.com/auth/shopify/callback", "https://twins-missouri-biotechnology-steady.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
